/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorksRouteImport } from './routes/works'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksIndexRouteImport } from './routes/works/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as WorksSomeonesFaceRouteImport } from './routes/works/someones-face'
import { Route as WorksDailyArchiveRouteImport } from './routes/works/daily-archive'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'

const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorksRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const WorksSomeonesFaceRoute = WorksSomeonesFaceRouteImport.update({
  id: '/someones-face',
  path: '/someones-face',
  getParentRoute: () => WorksRoute,
} as any)
const WorksDailyArchiveRoute = WorksDailyArchiveRouteImport.update({
  id: '/daily-archive',
  path: '/daily-archive',
  getParentRoute: () => WorksRoute,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteWithChildren
  '/works': typeof WorksRouteWithChildren
  '/posts/$slug': typeof PostsSlugRoute
  '/works/daily-archive': typeof WorksDailyArchiveRoute
  '/works/someones-face': typeof WorksSomeonesFaceRoute
  '/posts/': typeof PostsIndexRoute
  '/works/': typeof WorksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/works/daily-archive': typeof WorksDailyArchiveRoute
  '/works/someones-face': typeof WorksSomeonesFaceRoute
  '/posts': typeof PostsIndexRoute
  '/works': typeof WorksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteWithChildren
  '/works': typeof WorksRouteWithChildren
  '/posts/$slug': typeof PostsSlugRoute
  '/works/daily-archive': typeof WorksDailyArchiveRoute
  '/works/someones-face': typeof WorksSomeonesFaceRoute
  '/posts/': typeof PostsIndexRoute
  '/works/': typeof WorksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/works'
    | '/posts/$slug'
    | '/works/daily-archive'
    | '/works/someones-face'
    | '/posts/'
    | '/works/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/posts/$slug'
    | '/works/daily-archive'
    | '/works/someones-face'
    | '/posts'
    | '/works'
  id:
    | '__root__'
    | '/'
    | '/posts'
    | '/works'
    | '/posts/$slug'
    | '/works/daily-archive'
    | '/works/someones-face'
    | '/posts/'
    | '/works/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsRoute: typeof PostsRouteWithChildren
  WorksRoute: typeof WorksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/': {
      id: '/works/'
      path: '/'
      fullPath: '/works/'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof WorksRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/works/someones-face': {
      id: '/works/someones-face'
      path: '/someones-face'
      fullPath: '/works/someones-face'
      preLoaderRoute: typeof WorksSomeonesFaceRouteImport
      parentRoute: typeof WorksRoute
    }
    '/works/daily-archive': {
      id: '/works/daily-archive'
      path: '/daily-archive'
      fullPath: '/works/daily-archive'
      preLoaderRoute: typeof WorksDailyArchiveRouteImport
      parentRoute: typeof WorksRoute
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof PostsRoute
    }
  }
}

interface PostsRouteChildren {
  PostsSlugRoute: typeof PostsSlugRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsSlugRoute: PostsSlugRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface WorksRouteChildren {
  WorksDailyArchiveRoute: typeof WorksDailyArchiveRoute
  WorksSomeonesFaceRoute: typeof WorksSomeonesFaceRoute
  WorksIndexRoute: typeof WorksIndexRoute
}

const WorksRouteChildren: WorksRouteChildren = {
  WorksDailyArchiveRoute: WorksDailyArchiveRoute,
  WorksSomeonesFaceRoute: WorksSomeonesFaceRoute,
  WorksIndexRoute: WorksIndexRoute,
}

const WorksRouteWithChildren = WorksRoute._addFileChildren(WorksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsRoute: PostsRouteWithChildren,
  WorksRoute: WorksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
